# Generated by Django 4.1.10 on 2023-08-20 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='carausel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('sub_title', models.CharField(max_length=250, verbose_name='title')),
                ('docu', models.FileField(max_length=255, upload_to='images/')),
            ],
        ),
    ]
