# Generated by Django 4.2.4 on 2023-08-20 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='card1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='title')),
                ('sub_title', models.CharField(max_length=250, verbose_name='title')),
                ('docu', models.FileField(max_length=255, upload_to='images/')),
            ],
        ),
    ]
