# Generated by Django 4.2.4 on 2023-09-13 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_card2'),
    ]

    operations = [
        migrations.CreateModel(
            name='appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=50)),
                ('youraddress', models.CharField(max_length=50)),
                ('emailaddress', models.CharField(max_length=50)),
                ('yourage', models.DateField()),
                ('Date', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='carausel',
            name='sub_title',
            field=models.CharField(max_length=250, verbose_name='sub_title'),
        ),
        migrations.AlterField(
            model_name='card1',
            name='sub_title',
            field=models.CharField(max_length=250, verbose_name='sub_title'),
        ),
        migrations.AlterField(
            model_name='card2',
            name='title',
            field=models.CharField(max_length=50, verbose_name='Dr. Name'),
        ),
    ]
