# Generated by Django 4.2.5 on 2023-09-14 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_appointment_alter_carausel_sub_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='yourage',
            field=models.BigIntegerField(),
        ),
    ]
